name: check
on:
  pull_request:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix flake check --show-trace
