name: check
on:
  pull_request:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v20
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: cachix/cachix-action@v16
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix flake check --show-trace
