name: release
on:
  push:
    branches: [main, beta]
jobs:
  check:
    uses: ./.github/workflows/check.yml
  release:
    if: ${{ github.repository_owner == 'mirkolenz' }}
    runs-on: ubuntu-latest
    needs: check
    environment:
      name: release
      url: https://github.com/mirkolenz/makejinja/releases/tag/${{ steps.semanticrelease.outputs.git-tag }}
    permissions:
      contents: write
    outputs:
      version: ${{ steps.semanticrelease.outputs.version }}
      released: ${{ steps.semanticrelease.outputs.released }}
      git-head: ${{ steps.semanticrelease.outputs.git-head }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix profile install .#release-env
      - uses: cihelper/action-semanticrelease-uv@a1c285cab8f6c4cb14e841e869ea9f58def2024a # v1
        id: semanticrelease
        with:
          uv-publish: false
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
        with:
          name: uv-build
          path: ./dist
  deploy-docker:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.released == 'true' }}
    permissions:
      contents: read
      packages: write
    environment:
      name: release
      url: https://ghcr.io/mirkolenz/makejinja
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ needs.release.outputs.git-head }}
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4
        with:
          platforms: arm64
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
            accept-flake-config = true
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix run .#docker-manifest --impure
        env:
          VERSION: ${{ needs.release.outputs.version }}
          GH_TOKEN: ${{ github.token }}
  deploy-pypi:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.released == 'true' }}
    permissions:
      id-token: write
    environment:
      name: release
      url: https://pypi.org/project/makejinja/${{needs.release.outputs.version}}/
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: uv-build
          path: ./dist
      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
  build-docs:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.released == 'true' }}
    permissions:
      contents: read
      pages: read
    environment: github-pages
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ needs.release.outputs.git-head }}
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix build .#docs
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: ./result
  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
        id: deploy
